name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: pytest
        run: |
          pytest test

      # Build and deploy only on main branch to avoid pushing partial builds
      - name: Build site or docs
        if: github.ref == 'refs/heads/main'
        run: |
          # If you have a build step (e.g., Sphinx or mkdocs), do it here. Example:
          # pip install mkdocs
          # mkdocs build
          echo "Build step for static files..."

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          # This uses the built-in GITHUB_TOKEN so your workflow can push to gh-pages branch
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          # The folder that contains your built static files
          publish_dir: ./site  # replace with your actual build output folder
